# Server port
server.port=8080

# FreeMarker config
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8
spring.freemarker.expose-request-attributes=true
spring.freemarker.expose-session-attributes=false

# Custom 404 error page
server.error.whitelabel.enabled=false
