/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-13 20:25:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Login</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/Styles.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("body { margin:0; padding:40px; background: linear-gradient(120deg, #2980b9, #8e44ad); font-family: Arial, Helvetica, sans-serif; min-height:100vh; box-sizing:border-box; }\n");
      out.write("h2 { font-size:60px; margin-bottom:20px; color:white; }\n");
      out.write(".login-container { margin-top:30px; max-width:600px; padding:30px; background-color:rgba(255,255,255,0.15); border-radius:8px; }\n");
      out.write(".form-row { margin-bottom:20px; display:flex; align-items:center; }\n");
      out.write("label { font-size:28px; font-weight:bold; color:white; width:200px; margin-right:20px; }\n");
      out.write(".text-input { font-size:24px; padding:12px; width:400px; border:2px solid black; border-radius:4px; box-sizing:border-box; }\n");
      out.write("input[type=\"submit\"] { font-size:24px; padding:12px 30px; background-color:#1a73e8; color:white; border:none; border-radius:8px; cursor:pointer; margin-top:20px; }\n");
      out.write("input[type=\"submit\"]:hover { background-color:#1558b0; }\n");
      out.write(".error-msg { color:#ff4444; font-size:24px; margin-bottom:15px; font-weight:bold; padding:15px; background-color:rgba(255,0,0,0.2); border-radius:4px; border-left:4px solid #ff4444; }\n");
      out.write(".success-msg { color:yellowgreen; font-size:24px; margin-bottom:15px; font-weight:bold; padding:15px; background-color:rgba(0,255,0,0.1); border-radius:4px; border-left:4px solid yellowgreen; }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"page\">\n");
      out.write("\n");
      out.write("<h2>Login</h2>\n");
      out.write("\n");
 if (request.getParameter("error") != null) { 
      out.write("\n");
      out.write("<div class=\"error-msg\">❌ Email and password does not match</div>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("<form method=\"post\" action=\"Login\" class=\"login-container\">\n");
      out.write("\n");
      out.write("<div class=\"form-row\">\n");
      out.write("<label>Email</label>\n");
      out.write("<input class=\"text-input\" type=\"text\" name=\"email\" placeholder=\"Enter your email\" required>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"form-row\">\n");
      out.write("<label>Password</label>\n");
      out.write("<input class=\"text-input\" type=\"password\" name=\"password\" placeholder=\"Enter your password\" required>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<input type=\"submit\" value=\"Login\">\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
 if (request.getParameter("logout") != null) { 
      out.write("\n");
      out.write("<div class=\"success-msg\">✅ You are logged out. Please login again.</div>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
